/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/zaD8UCS3kee
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Syne } from 'next/font/google'
import { Comfortaa } from 'next/font/google'

syne({
  subsets: ['latin'],
  display: 'swap',
})

comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function bg() {
  return (
    (<div className="flex min-h-[100dvh] flex-col">
      <header className="sticky top-0 z-50 w-full bg-background/80 backdrop-blur-md">
        <div className="container flex h-16 items-center justify-between px-4 md:px-6">
          <Link href="#" className="flex items-center" prefetch={false}>
            <img
              src="/placeholder.svg"
              width="24"
              height="24"
              alt="Logo"
              className="h-6 w-6"
              style={{ aspectRatio: "24/24", objectFit: "cover" }} />
            <span className="ml-2 font-bold animate-bounce">Alfred Fianyo</span>
          </Link>
          <nav className="hidden space-x-4 md:flex">
            <Link
              href="#"
              className="text-sm font-medium hover:underline transition-colors duration-300"
              prefetch={false}>
              Home
            </Link>
            <Link
              href="#"
              className="text-sm font-medium hover:underline transition-colors duration-300"
              prefetch={false}>
              Projects
            </Link>
            <Link
              href="#"
              className="text-sm font-medium hover:underline transition-colors duration-300"
              prefetch={false}>
              About
            </Link>
            <Link
              href="#"
              className="text-sm font-medium hover:underline transition-colors duration-300"
              prefetch={false}>
              Contact
            </Link>
          </nav>
          <Button variant="outline" size="icon" className="md:hidden">
            <MenuIcon className="h-6 w-6" />
          </Button>
        </div>
      </header>
      <main className="flex-1">
        <section id="hero" className="w-full bg-muted py-12 md:py-24 lg:py-32">
          <div
            className="container flex flex-col items-center justify-center gap-8 px-4 md:px-6">
            <div className="w-full max-w-2xl animate-fade-in-up"></div>
            <div className="space-y-4 text-center animate-fade-in-up">
              <h1
                className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl">
                Welcome to my Portfolio
              </h1>
              <p className="max-w-[700px] text-muted-foreground md:text-xl">
                Explore my 3D-powered portfolio showcasing my expertise as a software engineer.
              </p>
            </div>
          </div>
        </section>
        <section id="projects" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid gap-8 px-4 md:px-6 lg:grid-cols-2">
            <div className="space-y-4 animate-fade-in-left">
              <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Featured Projects</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Explore My Work</h2>
              <p
                className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Check out some of my recent projects and see how I've used 3D technology to enhance the user experience.
              </p>
            </div>
            <div className="grid gap-4 animate-fade-in-right">
              <div className="group relative overflow-hidden rounded-lg">
                <img
                  src="/placeholder.svg"
                  width="400"
                  height="300"
                  alt="Project 1"
                  className="h-full w-full object-cover transition-all duration-300 group-hover:scale-105"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }} />
                <div
                  className="absolute inset-0 flex flex-col items-start justify-end bg-gradient-to-t from-[rgba(0,0,0,0.7)] to-[rgba(0,0,0,0)] p-4 transition-all duration-300 group-hover:bg-gradient-to-t group-hover:from-[rgba(0,0,0,0.5)] group-hover:to-[rgba(0,0,0,0.2)]">
                  <h3 className="text-xl font-bold text-primary-foreground">Project 1</h3>
                  <p className="mt-2 text-sm text-muted-foreground">
                    A 3D-powered web application that showcases my skills as a software engineer.
                  </p>
                </div>
              </div>
              <div className="group relative overflow-hidden rounded-lg">
                <img
                  src="/placeholder.svg"
                  width="400"
                  height="300"
                  alt="Project 2"
                  className="h-full w-full object-cover transition-all duration-300 group-hover:scale-105"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }} />
                <div
                  className="absolute inset-0 flex flex-col items-start justify-end bg-gradient-to-t from-[rgba(0,0,0,0.7)] to-[rgba(0,0,0,0)] p-4 transition-all duration-300 group-hover:bg-gradient-to-t group-hover:from-[rgba(0,0,0,0.5)] group-hover:to-[rgba(0,0,0,0.2)]">
                  <h3 className="text-xl font-bold text-primary-foreground">Project 2</h3>
                  <p className="mt-2 text-sm text-muted-foreground">
                    A 3D-powered web application that showcases my skills as a software engineer.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="about" className="w-full py-12 md:py-24 lg:py-32">
          <div
            className="container grid items-center justify-center gap-8 px-4 md:px-6 lg:grid-cols-2 lg:gap-16">
            <div className="space-y-4 animate-fade-in-left">
              <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">About Me</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">My Background</h2>
              <p
                className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                I am a passionate software engineer with a strong background in 3D technology. I have experience in
                creating visually stunning and interactive web applications that push the boundaries of what's possible
                on the web.
              </p>
            </div>
            <div className="grid gap-4 animate-fade-in-right">
              <img
                src="/placeholder.svg"
                width="400"
                height="300"
                alt="About Me"
                className="rounded-lg object-cover"
                style={{ aspectRatio: "400/300", objectFit: "cover" }} />
              <img
                src="/placeholder.svg"
                width="400"
                height="300"
                alt="About Me"
                className="rounded-lg object-cover"
                style={{ aspectRatio: "400/300", objectFit: "cover" }} />
            </div>
          </div>
        </section>
        <section id="contact" className="w-full bg-muted py-12 md:py-24 lg:py-32">
          <div
            className="container grid items-center justify-center gap-8 px-4 md:px-6 lg:grid-cols-2 lg:gap-16">
            <div className="space-y-4 animate-fade-in-left">
              <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Get in Touch</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Contact Me</h2>
              <p
                className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Feel free to reach out to me with any questions or inquiries about my work. I'd be happy to discuss
                potential collaborations or projects.
              </p>
            </div>
            <div className="rounded-lg bg-background p-6 shadow-lg animate-fade-in-right">
              <form className="grid gap-4">
                <Input type="text" placeholder="Name" className="w-full" />
                <Input type="email" placeholder="Email" className="w-full" />
                <Textarea placeholder="Message" className="w-full" rows={5} />
                <Button type="submit" className="w-full">
                  Send Message
                </Button>
              </form>
            </div>
          </div>
        </section>
      </main>
      <footer
        className="w-full bg-muted py-6 text-center text-sm text-muted-foreground">
        <div className="container px-4 md:px-6">&copy; 2024 Alfred Fianyo. All rights reserved.</div>
      </footer>
    </div>)
  );
}

function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}
