/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/cWE0F0kddXP
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Comfortaa } from 'next/font/google'

comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function projects() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header className="sticky top-0 z-50 w-full bg-background/80 backdrop-blur-sm">
        <div className="container flex h-16 items-center justify-between px-4 md:px-6">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <div className="relative h-8 w-8 rounded-full bg-muted">
              <img
                src="/placeholder.svg"
                alt="John Doe"
                fill
                className="rounded-full object-cover" />
            </div>
            <span className="font-bold">John Doe</span>
          </Link>
          <nav className="hidden space-x-4 md:flex">
            <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
              Home
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
              Projects
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
              Skills
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
              Contact
            </Link>
          </nav>
          <Button variant="ghost" size="icon" className="md:hidden">
            <MenuIcon className="h-6 w-6" />
          </Button>
        </div>
      </header>
      <main className="flex-1">
        <section
          id="hero"
          className="relative flex h-[80dvh] items-center justify-center bg-muted">
          <div className="container grid gap-6 px-4 md:grid-cols-2 md:gap-12">
            <div className="flex flex-col items-center justify-center space-y-4">
              <div className="relative h-48 w-48 sm:h-64 sm:w-64">
                <div>
                  <div />
                  <ambientLight />
                  <pointLight position={[10, 10, 10]} />
                  <mesh>
                    <boxGeometry args={[2, 2, 2]} />
                    <meshStandardMaterial color="#55efc4" />
                  </mesh>
                </div>
              </div>
              <div className="space-y-2 text-center">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">John Doe</h1>
                <p className="text-muted-foreground md:text-xl">Software Engineer | Full-Stack Developer</p>
              </div>
            </div>
            <div className="flex flex-col items-center justify-center space-y-4">
              <div className="prose max-w-md text-center text-muted-foreground">
                <p>
                  Hi, I'm John Doe, a passionate software engineer with a strong background in full-stack development. I
                  specialize in creating innovative and user-friendly web applications.
                </p>
                <p>
                  With a keen eye for design and a deep understanding of technology, I strive to deliver high-quality
                  solutions that solve real-world problems.
                </p>
              </div>
              <div className="flex gap-4">
                <Link
                  href="#"
                  className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}>
                  View Projects
                </Link>
                <Link
                  href="#"
                  className="inline-flex h-9 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}>
                  Contact Me
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section id="projects" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid gap-12 px-4 md:px-6">
            <div className="space-y-2 text-center">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">My Projects</h2>
              <p className="text-muted-foreground md:text-xl">Explore the projects I've worked on.</p>
            </div>
            <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
              <div className="relative h-[300px] w-full overflow-hidden rounded-lg">
                <div>
                  <div />
                  <ambientLight />
                  <pointLight position={[10, 10, 10]} />
                  <mesh>
                    <boxGeometry args={[2, 2, 2]} />
                    <meshStandardMaterial color="#55efc4" />
                  </mesh>
                </div>
                <div
                  className="absolute inset-0 flex flex-col items-center justify-center space-y-4 bg-background/80">
                  <h3 className="text-xl font-bold">Project 1</h3>
                  <p className="text-muted-foreground">A web application for managing tasks and projects.</p>
                  <div className="flex gap-4">
                    <Link
                      href="#"
                      className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}>
                      View Project
                    </Link>
                    <Link
                      href="#"
                      className="inline-flex h-9 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}>
                      GitHub
                    </Link>
                  </div>
                </div>
              </div>
              <div className="relative h-[300px] w-full overflow-hidden rounded-lg">
                <div>
                  <div />
                  <ambientLight />
                  <pointLight position={[10, 10, 10]} />
                  <mesh>
                    <boxGeometry args={[2, 2, 2]} />
                    <meshStandardMaterial color="#55efc4" />
                  </mesh>
                </div>
                <div
                  className="absolute inset-0 flex flex-col items-center justify-center space-y-4 bg-background/80">
                  <h3 className="text-xl font-bold">Project 2</h3>
                  <p className="text-muted-foreground">A responsive e-commerce website with a modern design.</p>
                  <div className="flex gap-4">
                    <Link
                      href="#"
                      className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}>
                      View Project
                    </Link>
                    <Link
                      href="#"
                      className="inline-flex h-9 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}>
                      GitHub
                    </Link>
                  </div>
                </div>
              </div>
              <div className="relative h-[300px] w-full overflow-hidden rounded-lg">
                <div>
                  <div />
                  <ambientLight />
                  <pointLight position={[10, 10, 10]} />
                  <mesh>
                    <boxGeometry args={[2, 2, 2]} />
                    <meshStandardMaterial color="#55efc4" />
                  </mesh>
                </div>
                <div
                  className="absolute inset-0 flex flex-col items-center justify-center space-y-4 bg-background/80">
                  <h3 className="text-xl font-bold">Project 3</h3>
                  <p className="text-muted-foreground">
                    A mobile-first web application for tracking personal finances.
                  </p>
                  <div className="flex gap-4">
                    <Link
                      href="#"
                      className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}>
                      View Project
                    </Link>
                    <Link
                      href="#"
                      className="inline-flex h-9 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}>
                      GitHub
                    </Link>
                  </div>
                </div>
              </div>
              <div className="relative h-[300px] w-full overflow-hidden rounded-lg">
                <div>
                  <div />
                  <ambientLight />
                  <pointLight position={[10, 10, 10]} />
                  <mesh>
                    <boxGeometry args={[2, 2, 2]} />
                    <meshStandardMaterial color="#55efc4" />
                  </mesh>
                </div>
                <div
                  className="absolute inset-0 flex flex-col items-center justify-center space-y-4 bg-background/80">
                  <h3 className="text-xl font-bold">Project 4</h3>
                  <p className="text-muted-foreground">A web-based chat application with real-time messaging.</p>
                  <div className="flex gap-4">
                    <Link
                      href="#"
                      className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}>
                      View Project
                    </Link>
                    <Link
                      href="#"
                      className="inline-flex h-9 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}>
                      GitHub
                    </Link>
                  </div>
                </div>
              </div>
              <div className="relative h-[300px] w-full overflow-hidden rounded-lg">
                <div>
                  <div />
                  <ambientLight />
                  <pointLight position={[10, 10, 10]} />
                  <mesh>
                    <boxGeometry args={[2, 2, 2]} />
                    <meshStandardMaterial color="#55efc4" />
                  </mesh>
                </div>
                <div
                  className="absolute inset-0 flex flex-col items-center justify-center space-y-4 bg-background/80">
                  <h3 className="text-xl font-bold">Project 5</h3>
                  <p className="text-muted-foreground">
                    A data visualization dashboard for tracking key business metrics.
                  </p>
                  <div className="flex gap-4">
                    <Link
                      href="#"
                      className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}>
                      View Project
                    </Link>
                    <Link
                      href="#"
                      className="inline-flex h-9 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}>
                      GitHub
                    </Link>
                  </div>
                </div>
              </div>
              <div className="relative h-[300px] w-full overflow-hidden rounded-lg">
                <div>
                  <div />
                  <ambientLight />
                  <pointLight position={[10, 10, 10]} />
                  <mesh>
                    <boxGeometry args={[2, 2, 2]} />
                    <meshStandardMaterial color="#55efc4" />
                  </mesh>
                </div>
                <div
                  className="absolute inset-0 flex flex-col items-center justify-center space-y-4 bg-background/80">
                  <h3 className="text-xl font-bold">Project 6</h3>
                  <p className="text-muted-foreground">A mobile-friendly blog platform with a modern design.</p>
                  <div className="flex gap-4">
                    <Link
                      href="#"
                      className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}>
                      View Project
                    </Link>
                    <Link
                      href="#"
                      className="inline-flex h-9 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none"
                      prefetch={false} />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>)
  );
}

function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}
